<?php
namespace Aws\CodeDeploy;

use Aws\AwsClient;

/**
 * This client is used to interact with AWS CodeDeploy
 *
 * @method \Aws\Result addTagsToOnPremisesInstances(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise addTagsToOnPremisesInstancesAsync(array $args = [])
 * @method \Aws\Result batchGetApplicationRevisions(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise batchGetApplicationRevisionsAsync(array $args = [])
 * @method \Aws\Result batchGetApplications(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise batchGetApplicationsAsync(array $args = [])
 * @method \Aws\Result batchGetDeploymentGroups(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise batchGetDeploymentGroupsAsync(array $args = [])
 * @method \Aws\Result batchGetDeploymentInstances(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise batchGetDeploymentInstancesAsync(array $args = [])
 * @method \Aws\Result batchGetDeployments(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise batchGetDeploymentsAsync(array $args = [])
 * @method \Aws\Result batchGetOnPremisesInstances(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise batchGetOnPremisesInstancesAsync(array $args = [])
 * @method \Aws\Result createApplication(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise createApplicationAsync(array $args = [])
 * @method \Aws\Result createDeployment(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise createDeploymentAsync(array $args = [])
 * @method \Aws\Result createDeploymentConfig(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise createDeploymentConfigAsync(array $args = [])
 * @method \Aws\Result createDeploymentGroup(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise createDeploymentGroupAsync(array $args = [])
 * @method \Aws\Result deleteApplication(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise deleteApplicationAsync(array $args = [])
 * @method \Aws\Result deleteDeploymentConfig(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise deleteDeploymentConfigAsync(array $args = [])
 * @method \Aws\Result deleteDeploymentGroup(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise deleteDeploymentGroupAsync(array $args = [])
 * @method \Aws\Result deregisterOnPremisesInstance(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise deregisterOnPremisesInstanceAsync(array $args = [])
 * @method \Aws\Result getApplication(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise getApplicationAsync(array $args = [])
 * @method \Aws\Result getApplicationRevision(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise getApplicationRevisionAsync(array $args = [])
 * @method \Aws\Result getDeployment(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise getDeploymentAsync(array $args = [])
 * @method \Aws\Result getDeploymentConfig(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise getDeploymentConfigAsync(array $args = [])
 * @method \Aws\Result getDeploymentGroup(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise getDeploymentGroupAsync(array $args = [])
 * @method \Aws\Result getDeploymentInstance(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise getDeploymentInstanceAsync(array $args = [])
 * @method \Aws\Result getOnPremisesInstance(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise getOnPremisesInstanceAsync(array $args = [])
 * @method \Aws\Result listApplicationRevisions(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listApplicationRevisionsAsync(array $args = [])
 * @method \Aws\Result listApplications(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listApplicationsAsync(array $args = [])
 * @method \Aws\Result listDeploymentConfigs(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listDeploymentConfigsAsync(array $args = [])
 * @method \Aws\Result listDeploymentGroups(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listDeploymentGroupsAsync(array $args = [])
 * @method \Aws\Result listDeploymentInstances(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listDeploymentInstancesAsync(array $args = [])
 * @method \Aws\Result listDeployments(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listDeploymentsAsync(array $args = [])
 * @method \Aws\Result listOnPremisesInstances(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listOnPremisesInstancesAsync(array $args = [])
 * @method \Aws\Result registerApplicationRevision(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise registerApplicationRevisionAsync(array $args = [])
 * @method \Aws\Result registerOnPremisesInstance(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise registerOnPremisesInstanceAsync(array $args = [])
 * @method \Aws\Result removeTagsFromOnPremisesInstances(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise removeTagsFromOnPremisesInstancesAsync(array $args = [])
 * @method \Aws\Result stopDeployment(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise stopDeploymentAsync(array $args = [])
 * @method \Aws\Result updateApplication(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise updateApplicationAsync(array $args = [])
 * @method \Aws\Result updateDeploymentGroup(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise updateDeploymentGroupAsync(array $args = [])
 */
class CodeDeployClient extends AwsClient {}
