<?php
namespace Aws\Inspector;

use Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Inspector** service.
 *
 * @method \Aws\Result addAttributesToFindings(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise addAttributesToFindingsAsync(array $args = [])
 * @method \Aws\Result createAssessmentTarget(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise createAssessmentTargetAsync(array $args = [])
 * @method \Aws\Result createAssessmentTemplate(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise createAssessmentTemplateAsync(array $args = [])
 * @method \Aws\Result createResourceGroup(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise createResourceGroupAsync(array $args = [])
 * @method \Aws\Result deleteAssessmentRun(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise deleteAssessmentRunAsync(array $args = [])
 * @method \Aws\Result deleteAssessmentTarget(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise deleteAssessmentTargetAsync(array $args = [])
 * @method \Aws\Result deleteAssessmentTemplate(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise deleteAssessmentTemplateAsync(array $args = [])
 * @method \Aws\Result describeAssessmentRuns(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise describeAssessmentRunsAsync(array $args = [])
 * @method \Aws\Result describeAssessmentTargets(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise describeAssessmentTargetsAsync(array $args = [])
 * @method \Aws\Result describeAssessmentTemplates(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise describeAssessmentTemplatesAsync(array $args = [])
 * @method \Aws\Result describeCrossAccountAccessRole(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise describeCrossAccountAccessRoleAsync(array $args = [])
 * @method \Aws\Result describeFindings(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise describeFindingsAsync(array $args = [])
 * @method \Aws\Result describeResourceGroups(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise describeResourceGroupsAsync(array $args = [])
 * @method \Aws\Result describeRulesPackages(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise describeRulesPackagesAsync(array $args = [])
 * @method \Aws\Result getTelemetryMetadata(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise getTelemetryMetadataAsync(array $args = [])
 * @method \Aws\Result listAssessmentRunAgents(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listAssessmentRunAgentsAsync(array $args = [])
 * @method \Aws\Result listAssessmentRuns(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listAssessmentRunsAsync(array $args = [])
 * @method \Aws\Result listAssessmentTargets(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listAssessmentTargetsAsync(array $args = [])
 * @method \Aws\Result listAssessmentTemplates(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listAssessmentTemplatesAsync(array $args = [])
 * @method \Aws\Result listEventSubscriptions(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listEventSubscriptionsAsync(array $args = [])
 * @method \Aws\Result listFindings(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listFindingsAsync(array $args = [])
 * @method \Aws\Result listRulesPackages(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listRulesPackagesAsync(array $args = [])
 * @method \Aws\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \Aws\Result previewAgents(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise previewAgentsAsync(array $args = [])
 * @method \Aws\Result registerCrossAccountAccessRole(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise registerCrossAccountAccessRoleAsync(array $args = [])
 * @method \Aws\Result removeAttributesFromFindings(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise removeAttributesFromFindingsAsync(array $args = [])
 * @method \Aws\Result setTagsForResource(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise setTagsForResourceAsync(array $args = [])
 * @method \Aws\Result startAssessmentRun(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise startAssessmentRunAsync(array $args = [])
 * @method \Aws\Result stopAssessmentRun(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise stopAssessmentRunAsync(array $args = [])
 * @method \Aws\Result subscribeToEvent(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise subscribeToEventAsync(array $args = [])
 * @method \Aws\Result unsubscribeFromEvent(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise unsubscribeFromEventAsync(array $args = [])
 * @method \Aws\Result updateAssessmentTarget(array $args = [])
 * @method \GuzzleHttpv6\Promise\Promise updateAssessmentTargetAsync(array $args = [])
 */
class InspectorClient extends AwsClient {}
